### ISSUE TITLE
Print statements in SPM version.

### ISSUE THREAD

**Issue by bwees** [Jake-Short/swiftui-image-viewer#13]
Hello, there are 3 print statements that are present in the SPM version that are not present in the Github repo. They are in the onEnded section of the drag gesture. They are: 
`print(abs(self.dragOffset.height) + abs(self.dragOffset.width))`
 `print((abs(self.dragOffsetPredicted.height)) / (abs(self.dragOffset.height)))`
`print((abs(self.dragOffsetPredicted.width)) / (abs(self.dragOffset.width)))`

**Comment by Jake-Short** [comment]
Thank you for reporting this. It appears to be a bug with the version tagging. By bumping up the tag to 1.0.23 (without any additional changes), the issue appears to have been fixed.
