### ISSUE TITLE
Captions for images

### ISSUE THREAD

**Issue by Jiuzhen** [Jake-Short/swiftui-image-viewer#18]
Hi,
The image viewer works great! And I would like to have a small suggestion: 
Is it possible to add a modifier to display captions? 

Thanks!! 🎊

**See attached image**
![simulator_screenshot_4813FDE3-B5F7-4DC3-AC11-4B671291C37D](https://user-images.githubusercontent.com/13263720/101312945-e901c300-3809-11eb-85d3-bbf6248cf612.png)

**Comment by Jake-Short** [comment]
This is a really good idea, thank you! I have created a PR and will get it merged in soon.
