### ISSUE TITLE
ImageViewerRemote wants a valid URL too early

### ISSUE THREAD

**Issue by jeanmartin** [Jake-Short/swiftui-image-viewer#21]
**Describe the bug**
Using `ImageViewerRemote` the URL string has to be a valid URL even if viewerShown is false.

**To Reproduce**
With these vars:
```swift
@State var selectedURL: String = ""
@State var imageSelected: Bool = false
```
and this in my view:
```swift
.overlay(ImageViewerRemote(imageURL: $selectedURL, viewerShown: $imageSelected))
```
I get an unexpected nil when unwrapping because of line 314 in ImageViewerRemote.swift (`let url = URL(string: url)!`).

**Expected behavior**
I expect to only need a valid URL (string) in my `$selectedURL` if `$imageSelected` is true.
Since the selectedURL is a binding it is commonly set at some point during user interaction but won't have a meaningful value before that.

**Device Information (please complete the following information):**
- Device/simulator: iPhone 12 Pro
- iOS version: 14.3

**Desktop (please complete the following information):**
 - macOS: macOS 11.1
 - Xcode version: 12.3 (12C33)

**Comment by Jake-Short** [comment]
Thanks for reporting this, it has been fixed in PR #22 .
