### ISSUE TITLE
Can we move the close btn to right top?

### ISSUE THREAD

**Issue by wiidz** [Jake-Short/swiftui-image-viewer#24]
I got a navigation back btn on left top.
So when i using swiftui-image-viewer , the navigation back btn will cover the close btn of image viewer.
Can we custom the position of close btn ?

By the way , this image viewer helps me a lot.

Thx ! :)

**Comment by Jake-Short** [comment]
Yep, great idea! I’ll work on that and hopefully get it out really soon.
