### ISSUE TITLE
Can not install dependecy

### ISSUE THREAD

**Issue by myronovych** [Jake-Short/swiftui-image-viewer#3]
Hi, I saw your creation and that's exactly what I need in my project. However, when I try to install it, XCode gives me an error. 
![Снимок экрана 2020-07-14 в 17 03 52](https://user-images.githubusercontent.com/43410212/87435145-fff20f80-c5f3-11ea-8b13-30b6fe3f5731.png)
Thanks.

**Comment by Jake-Short** [comment]
This issue should hopefully be resolved alongside the latest release (1.0.15). There appeared to be an issue with the url-image dependancy. If you run into any trouble let me know!

**Comment by myronovych** [comment]
Thanks for response! Tried again, but didn't work. Let me know if you need any other information.
![image](https://user-images.githubusercontent.com/43410212/87465727-cd5d0c80-c61d-11ea-8fb5-1fca5c96debc.png)

**Comment by Jake-Short** [comment]
Interesting, I've been trying to reproduce this but I haven't been able to so far. Can you share some more details to reproduce this, such as:

- Xcode/macOS version
- Other SPM dependencies installed
- Deployment targets (iOS, macOS, etc.) and versions (iOS 13/14)

And any other information that you believe would be helpful to reproduce this bug.

**Comment by myronovych** [comment]
-  Version 11.3.1 (11C504)/macOS Catalina (10.15.3)

- none, but have installed FirebaseAuth with cocoapods

- IOS simulator version 11.3.1, IOS 13.3

Other information: 
I don't know if it plays any role, but when I press "Add package dependency" I have next window -> 
![image](https://user-images.githubusercontent.com/43410212/87466899-c1724a00-c61f-11ea-8b55-b00f3b5090fa.png)

here I choose "ZNOshka" (my project name)

Then I choose rules such as "Version: up to next major: 1.0.15 < 2.0.0"
![image](https://user-images.githubusercontent.com/43410212/87467029-f67e9c80-c61f-11ea-9ef7-475f0684aea5.png)

**Comment by Jake-Short** [comment]
The issue was that the package used Swift tools version 5.2, which is not compatible with Xcode 11.3.1. In the latest update (1.0.18), I reduced the Swift tools version to version 5.1, which allows compatibility with Xcode 11.3.1. Let me know if you run into any issues.

**Comment by myronovych** [comment]
Awesome will try that tomorrow! Thanks for your help!
Also, I saw in your profile that you are WWDC SSC Winner, congrats with that! Can I see your project somewhere? Just really interested in what you have done :)

**Comment by Jake-Short** [comment]
Thanks! I just put the repo up here: https://github.com/Jake-Short/wwdc-2020-mood-predictor.

I've been meaning to get screenshots/videos of it, but I am running macOS Big Sur and there appears to be a bug preventing me from running the playground. But you can still see the code if you would like!

**Comment by myronovych** [comment]
Thank you!🙏🏼🙏🏼🙏🏼
