### ISSUE TITLE
Caption text doesnt response change

### ISSUE THREAD

**Issue by 0xcaffebabe** [Jake-Short/swiftui-image-viewer#36]
**Describe the bug**

**To Reproduce**

add caption params:

```swift
@State var imgDesc: String = "default"
...
ImageViewerRemote(imageURL: self.$imgURL, viewerShown: self.$showImageViewer, caption: Text(imgDesc), closeButtonTopRight: true)
```

when change imgDesc's value, the caption doesnt change, it still is 'default'

**Expected behavior**
caption value shoud be change to new value

**Comment by 0xcaffebabe** [comment]
beginner, dont understand the swiftui mechanism

**Comment by Jake-Short** [comment]
Sorry for my delayed response, but I'm glad you figured it out!
