### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by bwees** [Jake-Short/swiftui-image-viewer#6]
Hello, I get the following error when i try to install the package:

<img width="666" alt="Screen Shot 2020-07-19 at 5 51 19 PM" src="https://user-images.githubusercontent.com/12686250/87886126-89d11c80-c9e8-11ea-8711-6dd86db3e85b.png">

I am on Xcode 11.6 and ios 13.6

**Comment by Jake-Short** [comment]
Thanks for reporting this, I was able to reproduce it and fix it in the latest release (1.0.19). Let me know if you run into anymore issues!
